### pay
POST http://localhost:8080/pay
content-type: application/json

{
  "account": "123",
  "type": 3,
  "product": "A",
  "amount": 10
}

### suggest
GET http://localhost:8080/suggest?username=rice